num=[1,2,3,4,5]
print("Before Append num: ",num)
num.append(6)
print("When Append num: ",num)
print("Before Insert num: ",num)
num.insert(3,10)
print("When Insert num: ",num)
print("Before Remove num: ",num)
num.remove(10)
print("When Remove num: ",num)
last_num=num.pop()
print("When Pop num: ",last_num)
index=num.index(3)
print("Index of 3 is: ",index)
count=num.count(2)
print("Count of 2 is: ",count)
num.insert(2 ,10)
num.insert(3 ,11)
num.insert(4 ,9)
print("After inserted and unsorted num: ",num)
sorted_num=sorted(num)
print("When Sorted num: ",sorted_num)
